proxy:
  # Address and port of the proxy server.
  host: localhost:8000
  # Optional, in bytes, default: 4MiB.
  max-request-body-size: 4096

# Optional, enables API server.
api:
  # Address and port of the API server.
  host: localhost:3000
